#server:
#  servlet:
#    context-path: /api

#management:
#  endpoint:
#    shutdown:
#      enabled: true

#server:
#  port: 8080

#spring:
#  mail:
#    host: smtp.gmail.com
#    port: 578
#    username:
#    password:
#    properties:
#      mail:
#        smtp:
#          auth: true
#          starttls:
#            enable: true

#life-stater:
#  export:
#    uri: test

logging.level.org.mongodb.driver: ERROR